package model.items.questfinds.maps;

import utils.items.QuestFind;
import utils.collections.Collectable;

public enum WolvenSchoolGearMaps implements QuestFind, Collectable {
    WELLPRESERVED_NOTES_BY_HIERONYMUS_ON_THE_WITCHER_ELGAR,
    SLIGHTLY_TORN_NOTES_BY_HIERONYMUS_ON_THE_WITCHER_ELGAR,
    DAMP_MOLDY_NOTES_BY_HIERONYMUS_ON_THE_WITCHER_ELGAR,
    HEAVILY_FADED_NOTES_BY_HIERONYMUS_ON_THE_WITCHER_ELGAR,
    WORNOUT_AND_FADED_NOTES_BY_HIERONYMUS_ON_THE_WITCHER_ELGAR,
    NOTES_ON_PARCHMENT_BY_HIERONYMUS_ON_ELGAR_THE_WITCHER
}
